version: 2
jobs:
  build:
    working_directory: ~/.circleci
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: | # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            python testTest.py
